### ISSUE TITLE
Increase brightness of `terminal.ansiWhite`

### ISSUE THREAD

**Issue by datho7561** [Miezhiko/hot-emo-theme#1]
Hello! Thanks for making this great theme!

I find it hard to read text in the integrated terminal that uses `terminal.ansiWhite` as a foreground and a colour as a background. I think this could be improved if the brightness of `terminal.ansiWhite` was increased.

For instance, my shell prompt:
![ShellPromptHotEmo](https://user-images.githubusercontent.com/22376627/96634291-4b4d4580-12e8-11eb-8e3a-1bcce25df890.png)

With `terminal.ansiWhite` set to `#f5eaf5`, its a bit easier to read:
![ShellPromptHotEmoPatched](https://user-images.githubusercontent.com/22376627/96634943-38874080-12e9-11eb-89c5-d1b70f642a61.png)

I understand if you don't want to change this colour. I just want to bring this to your attention.

**Comment by Miezhiko** [comment]
I can do it!

**Comment by Miezhiko** [comment]
I think... will check how does it looks like on my terminal

**Comment by Miezhiko** [comment]
I think f5eaf5 is very bright and good for terminal.ansiBrightWhite (at least ansiBrightWhite for sure should be brighter than White)

**Comment by Miezhiko** [comment]
then possibly something alike a597a1 for just white?

**Comment by Miezhiko** [comment]
But I can't publish new version, something is wrong with their marketplace 
![image](https://user-images.githubusercontent.com/38455533/96682318-af741600-1389-11eb-9828-efdc0c6e263c.png)

**Comment by datho7561** [comment]
Hmm. Okay.

**Comment by Miezhiko** [comment]
@datho7561 published
